INSERT INTO GITHUB_REPOSITORY(FULL_NAME, DESCRIPTION, CLONE_URL, STARS, CREATED_AT) VALUES ('wasilewskyy/test1', 'description1','url1', 1,'2025-06-01');
INSERT INTO GITHUB_REPOSITORY(FULL_NAME, DESCRIPTION, CLONE_URL, STARS, CREATED_AT) VALUES ('wasilewskyy/test2', 'description2','url2',2,'2025-06-02');
INSERT INTO GITHUB_REPOSITORY(FULL_NAME, DESCRIPTION, CLONE_URL, STARS, CREATED_AT) VALUES ('wasilewskyy/test3', 'description3', 'url3',3,'2025-06-03');
INSERT INTO GITHUB_REPOSITORY(FULL_NAME, DESCRIPTION, CLONE_URL, STARS, CREATED_AT) VALUES ('wasilewskyy/test4', 'description4','url4',4,'2025-06-04');
INSERT INTO GITHUB_REPOSITORY(FULL_NAME, DESCRIPTION, CLONE_URL, STARS, CREATED_AT) VALUES ('wasilewskyy/test5', 'description5','url5',5,'2025-06-05');